[project]
name = "burn-emulator"
authors = ["Burn Emulator Team"]
description = "A framework for token burning and emulation on Stacks"
telemetry = false
requirements = []

[contracts.authorization-manager]
path = "contracts/authorization-manager.clar"
depends_on = []

[contracts.burn-registry]
path = "contracts/burn-registry.clar"
depends_on = ["authorization-manager"]

[contracts.event-logger]
path = "contracts/event-logger.clar"
depends_on = ["authorization-manager"]

[contracts.token-adapter]
path = "contracts/token-adapter.clar"
depends_on = ["authorization-manager"]

[contracts.burn-emulator]
path = "contracts/burn-emulator.clar"
depends_on = ["burn-registry", "token-adapter", "event-logger"]

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
